server:
  port: ${server_port:8088}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:mysql://${db_host:127.0.0.1}:${db_port:5432}/${db_name:postgres}?useSSL=true
    username: ${db_username:postgres}
    password: ${db_password:postgres}
  application:
    name: ${spring_application-name:postgresql-loadbalancer}